# 使用pickle序列化numpy array

In [3]:
import pickle
import numpy as np

In [6]:
x = np.arange(10)

In [7]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
f = open('x.pkl','wb')

In [11]:
pickle.dump(x,f)

In [17]:
!ls

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [18]:
f = open('x.pkl','rb')

In [19]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.save('one_array',x)

In [21]:
!ls

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [22]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
y = np.arange(20)

In [24]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
np.savez('two_array.npz',a=x, b=y)

In [26]:
!ls

'ls' is not recognized as an internal or external command,
operable program or batch file.


In [28]:
c = np.load('two_array.npz')

In [29]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])