# 快速创建数组

In [1]:
import numpy as np

In [2]:
np.random.randn(10)

array([-0.67027966, -0.89229267, -0.08965943, -0.51641219, -0.22509031,
        0.39019743,  0.68318989, -0.19288655, -1.04116499,  0.92728084])

In [3]:
np.random.randint(10, size=(2,3))

array([[4, 0, 2],
       [9, 2, 1]])

In [4]:
np.random.randint(10,size=20)

array([0, 4, 7, 4, 9, 0, 2, 1, 7, 5, 3, 9, 7, 0, 7, 7, 5, 7, 2, 6])

In [5]:
np.random.randint(10,size=20).reshape(4,5)

array([[3, 8, 6, 3, 2],
       [5, 8, 4, 5, 0],
       [0, 2, 1, 2, 9],
       [8, 0, 4, 3, 0]])

# 数组运算

In [6]:
a = np.random.randint(10,size=20).reshape(4,5)

In [7]:
a

array([[1, 5, 8, 2, 0],
       [1, 8, 8, 0, 0],
       [7, 7, 1, 0, 4],
       [2, 0, 2, 8, 8]])

In [8]:
b = np.random.randint(10,size=20).reshape(4,5)

In [10]:
b

array([[8, 0, 1, 6, 0],
       [8, 9, 3, 3, 9],
       [7, 1, 3, 5, 2],
       [8, 1, 4, 2, 3]])

In [11]:
a+b

array([[ 9,  5,  9,  8,  0],
       [ 9, 17, 11,  3,  9],
       [14,  8,  4,  5,  6],
       [10,  1,  6, 10, 11]])

In [13]:
a-b

array([[-7,  5,  7, -4,  0],
       [-7, -1,  5, -3, -9],
       [ 0,  6, -2, -5,  2],
       [-6, -1, -2,  6,  5]])

In [14]:
a*b

array([[ 8,  0,  8, 12,  0],
       [ 8, 72, 24,  0,  0],
       [49,  7,  3,  0,  8],
       [16,  0,  8, 16, 24]])

In [15]:
a/b

C:\Users\LING\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\LING\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[0.125     ,        inf, 8.        , 0.33333333,        nan],
       [0.125     , 0.88888889, 2.66666667, 0.        , 0.        ],
       [1.        , 7.        , 0.33333333, 0.        , 2.        ],
       [0.25      , 0.        , 0.5       , 4.        , 2.66666667]])

In [17]:
np.matrix([[1,2,3],[4,5,6]])

matrix([[1, 2, 3],
        [4, 5, 6]])

In [18]:
np.mat(a)

matrix([[1, 5, 8, 2, 0],
        [1, 8, 8, 0, 0],
        [7, 7, 1, 0, 4],
        [2, 0, 2, 8, 8]])

# 矩阵的运算

In [19]:
A = np.mat(a)

In [20]:
B = np.mat(b)

In [21]:
A

matrix([[1, 5, 8, 2, 0],
        [1, 8, 8, 0, 0],
        [7, 7, 1, 0, 4],
        [2, 0, 2, 8, 8]])

In [22]:
B

matrix([[8, 0, 1, 6, 0],
        [8, 9, 3, 3, 9],
        [7, 1, 3, 5, 2],
        [8, 1, 4, 2, 3]])

In [23]:
A + B

matrix([[ 9,  5,  9,  8,  0],
        [ 9, 17, 11,  3,  9],
        [14,  8,  4,  5,  6],
        [10,  1,  6, 10, 11]])

In [24]:
A - B

matrix([[-7,  5,  7, -4,  0],
        [-7, -1,  5, -3, -9],
        [ 0,  6, -2, -5,  2],
        [-6, -1, -2,  6,  5]])

In [30]:
a = np.mat(np.random.randint(10,size=20).reshape(4,5))
b = np.mat(np.random.randint(10,size=20).reshape(5,4))

In [31]:
a

matrix([[2, 6, 7, 9, 9],
        [3, 9, 9, 4, 7],
        [8, 4, 9, 9, 5],
        [6, 7, 2, 3, 0]])

In [32]:
b

matrix([[5, 6, 8, 1],
        [7, 5, 1, 3],
        [6, 7, 3, 6],
        [2, 4, 5, 6],
        [7, 8, 5, 3]])

In [33]:
a * b

matrix([[175, 199, 133, 143],
        [189, 198, 115, 129],
        [175, 207, 165, 143],
        [ 97,  97,  76,  57]])

# Array常用函数

In [34]:
a = np.random.randint(10,size=20).reshape(4,5)

In [35]:
np.unique(a)

array([0, 1, 2, 3, 5, 6, 7, 8, 9])

In [36]:
a

array([[2, 5, 8, 1, 0],
       [6, 1, 3, 9, 2],
       [3, 2, 7, 1, 8],
       [2, 0, 7, 9, 8]])

In [37]:
sum(a)

array([13,  8, 25, 20, 18])

In [38]:
sum(a[0])

16

In [40]:
sum(a[:,0])

13

In [41]:
a.max()

9

In [42]:
max(a[0])

8

In [44]:
max(a[:,0])

6

# 使用pickle序列化numpy array