In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

# Concatenate

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
arr2 = np.arange(9).reshape(3,3)

In [7]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
np.concatenate([arr1,arr2])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.concatenate([arr1,arr2],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [10]:
s1 = Series([1,2,3],index=['X','Y','Z'])

In [11]:
s2 = Series([4,5],index=['A','B'])

In [12]:
s1

X    1
Y    2
Z    3
dtype: int64

In [13]:
s2

A    4
B    5
dtype: int64

In [14]:
pd.concat([s1,s2])

X    1
Y    2
Z    3
A    4
B    5
dtype: int64

In [17]:
pd.concat([s1,s2],axis=1)

C:\Users\LING\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
A  NaN  4.0
B  NaN  5.0
X  1.0  NaN
Y  2.0  NaN
Z  3.0  NaN

In [20]:
df1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

In [21]:
df1

X         Y         Z
0 -1.057855 -0.818781  0.742999
1  0.828009 -2.008731  1.181964
2  1.259186  0.705676 -0.422417
3 -0.944915 -1.150301  0.942122

In [22]:
df2 = DataFrame(np.random.randn(3,3),columns=['X','Y','A'])

In [23]:
df2

X         Y         A
0 -0.174874  1.578620  0.273994
1 -1.555538 -0.768152 -0.300911
2 -0.762425  0.351887 -3.125134

In [26]:
pd.concat([df1,df2])

C:\Users\LING\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


A         X         Y         Z
0       NaN -1.057855 -0.818781  0.742999
1       NaN  0.828009 -2.008731  1.181964
2       NaN  1.259186  0.705676 -0.422417
3       NaN -0.944915 -1.150301  0.942122
0  0.273994 -0.174874  1.578620       NaN
1 -0.300911 -1.555538 -0.768152       NaN
2 -3.125134 -0.762425  0.351887       NaN

In [27]:
#For more info in documentation:
url='http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'

# Combine

In [29]:
s1 = Series([2,np.nan,4,np.nan],index=['A','B','C','D'])

In [31]:
s1

A    2.0
B    NaN
C    4.0
D    NaN
dtype: float64

In [32]:
s2 = Series([1,2,3,4],index=['A','B','C','D'])

In [33]:
s2

A    1
B    2
C    3
D    4
dtype: int64

In [34]:
#用s2的值填充s1中没有的
s1.combine_first(s2)

A    2.0
B    2.0
C    4.0
D    4.0
dtype: float64

In [41]:
df1 = DataFrame({
    'X':[1,np.nan,3, np.nan],
    'Y':[5,np.nan,7, np.nan],
    'Z':[9,np.nan,11, np.nan]
})

In [42]:
df1

X    Y     Z
0  1.0  5.0   9.0
1  NaN  NaN   NaN
2  3.0  7.0  11.0
3  NaN  NaN   NaN

In [39]:
df2 = DataFrame({
    'Z':[np.nan,10, np.nan,12],
    'A':[1,2,3,4]
})

In [40]:
df2

Z  A
0   NaN  1
1  10.0  2
2   NaN  3
3  12.0  4

In [43]:
df1.combine_first(df2)

A    X    Y     Z
0  1.0  1.0  5.0   9.0
1  2.0  NaN  NaN  10.0
2  3.0  3.0  7.0  11.0
3  4.0  NaN  NaN  12.0